---
# yamllint config file
# see https://github.com/adrienverge/yamllint

extends: default

rules:
  line-length:
    max: 120
    level: warning
  octal-values:
    forbid-implicit-octal: true
  truthy:
    level: error
    check-keys: false
  comments:
    min-spaces-from-content: 1
